[desktop] Attempt to solve synchronization issue with HexHivePanel
This might be happening because the drawingProperties object might be rewritten during the path formation when the user clicks on another transfer.

ava.awt.geom.IllegalPathStateException: missing initial moveto in path definition
at java.awt.geom.Path2D.needRoom(Path2D.java:324)
at java.awt.geom.Path2D.lineTo(Path2D.java:438)
at com.frostwire.gui.components.transfers.HexHivePanel.drawHexagon(HexHivePanel.java:233)