[android] Don't crash on illegal state
Looks like this is being called twice, or there's a timing bug. Don't choke on this
as it probably happened already.

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1280)
    at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:451)
    at android.app.Activity.onBackPressed(Activity.java:2153)
    at com.frostwire.android.gui.activities.VPNStatusDetailActivity.onBackPressed(VPNStatusDetailActivity.java:159)