[android] reverting androidx.media2:media2*:1.1.1 to 1.0.3 - Incompatible with MoPub 5.15
Causes the following NoSuchMethodError crash
java.lang.NoSuchMethodError:
  at com.mopub.mobileads.VastVideoViewController.onPause (VastVideoViewController.java:518)
  at com.mopub.mobileads.FullscreenAdController.pause (FullscreenAdController.java:276)
  at com.mopub.mobileads.MoPubFullscreenActivity.onPause (MoPubFullscreenActivity.java:109)
  at android.app.Activity.performPause (Activity.java:7988)
  at android.app.Instrumentation.callActivityOnPause (Instrumentation.java:1508)
  at android.app.ActivityThread.performPauseActivityIfNeeded (ActivityThread.java:4567)
  at android.app.ActivityThread.performPauseActivity (ActivityThread.java:4528)
  at android.app.ActivityThread.handlePauseActivity (ActivityThread.java:4480)
  at android.app.servertransaction.PauseActivityItem.execute (PauseActivityItem.java:46)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread.handleMessage (ActivityThread.java:2058)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7573)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:937)